_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide


  column-sizes:
    col-6: one half
    col-12: full width
    col-4: one third
    col-3: one quarter
    col-6_sm-12: one half (mobile responsive)
    col-4_sm-12: one third (mobile responsive)
    col-3_sm-12: one quarter (mobile responsive)

collections:
  posts:
    output: true
    permalink: /articles/:slug
  booking:
    output: true
    permalink: /booking/:slug


_comments:
  title: Max 70 characters
  description: 165 characters
  social_image: Landscape 1200 x 627 px
  twitter_card: summary, photo, video, product, app, gallery
  twitter_description: 200 characters