_select_data:
  aspect-ratios:
    - Square
    - Portrait
    - Portrait-tall
    - Landscape
    - Landscape-wide

  column-sizes:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half (mobile responsive)
    col-4_sm-12: One Third (mobile responsive)
    col-3_sm-12: One Quarter (mobile responsive)