paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  title:
    type: text
    comment: Max 70 characters
    cascade: true
  description:
    type: textarea
    comment: 165 characters
    cascade: true
  social_image:
    type: image
    comment: Landscape 1200 x 627 px
    cascade: true
  twitter_card:
    type: text
    comment: summary, photo, video, product, app, gallery
    cascade: true
  twitter_description:
    type: textarea
    comment: 200 characters
    cascade: true
_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide
  column-sizes:
    col-6: one half
    col-12: full width
    col-4: one third
    col-3: one quarter
    col-6_sm-12: one half (mobile responsive)
    col-4_sm-12: one third (mobile responsive)
    col-3_sm-12: one quarter (mobile responsive)
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
