seo:
  site_name: Experience Hegra
  title: Experience Hegra 
  description:
  social_image:
  twitter_card:
  twitter_description:
  keywords:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark_color: '#3c3c3c'
  light_color: '#787878'
  white_color: '#ffffff'
