seo:
  site_name: Experience Hegra
  title: Experience Hegra 
  description: Experience Hegra, Saudi Arabia's first UNESCO World Heritage Site, in AlUla. Book your experiences and read articles about the largest Nabataean city south of Petra.
  social_image:
  twitter_card:
  twitter_description: Experience Hegra, Saudi Arabia's first UNESCO World Heritage Site. Book your experiences and read articles about the largest Nabataean city south of Petra — found in the modern-day city of AlUla, KSA.
  keywords:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark_color: '#3c3c3c'
  light_color: '#787878'
  white_color: '#ffffff'
